image:
  - Ubuntu
  - Visual Studio 2019

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

only_commits:
  files:
    - package.json

environment:
  matrix:
    - nodejs_version: 13
  GH_TOKEN:
    secure: khOgHhUwzVHSm3rDvpkFL8AgEj1DKOruKC4dB2qzPCTzYWs9ySBqpvA3BA6DnkgA
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

cache:
  #- '%LOCALAPPDATA%/Yarn'
  #- node_modules
  #- flow-typed
  #- '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - sh: sudo apt update && sudo apt-get install alien -y && sudo snap install snapcraft --classic
  - set CI=true
  - yarn
  - yarn package-ci
