image:
  - Visual Studio 2017
  - Ubuntu

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 12
  GH_TOKEN:
    secure: khOgHhUwzVHSm3rDvpkFL8AgEj1DKOruKC4dB2qzPCTzYWs9ySBqpvA3BA6DnkgA

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules
  - flow-typed
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: nvm install $nodejs_version
  - sh: sudo apt update && sudo apt-get install alien -y
  - set CI=true
  - yarn

test_script:
  - yarn package-ci
  - yarn lint
  # - yarn flow
  # - yarn test
  # - yarn build-e2e
  # - yarn test-e2e
  
deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: khOgHhUwzVHSm3rDvpkFL8AgEj1DKOruKC4dB2qzPCTzYWs9ySBqpvA3BA6DnkgA # your encrypted token from GitHub
  artifact: /.*\.(msi|exe|rpm|deb|snap|AppImage)/            # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
