name: Increment Wizard Version

on:
  repository_dispatch:
    types: [api-update]
  push:
    branches:
      - "master"

jobs:
  incrementVersion:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name: "cd app"
        run: cd app && apt install git -y
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: add shockapi@shocknet/api#${{ github.event.client_payload.ref }}
      - name: "cd ../"
        run: cd ../
      - name: 'Automated Version Bump (/app/package.json)'
        uses: 'Emad-salah/gh-action-bump-version@patch-2'
        with:
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "app"
      - name: 'Automated Version Bump (/package.json)'
        uses: 'Emad-salah/gh-action-bump-version@patch-2'
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "cat app/package.json"
        run: cat ./app/package.json
